# Adapted from https://blog.testproject.io/2021/02/01/using-github-actions-to-run-automated-tests/
name: pull-request
on:
  pull_request:
    # branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: ng test --browsers=ChromeHeadless --watch=false
