# Adapted from https://blog.testproject.io/2021/02/01/using-github-actions-to-run-automated-tests/
name: pull-request
on:
  pull_request:
    # branches: [ main ]

jobs:
  unit-test:
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    runs-on: ubuntu-latest
    name: unit-test-${{ matrix.browser }}
    steps:
      - uses: actions/checkout@v2
      # `cache` option uses https://github.com/actions/cache under the hood with less config.
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run test:${{matrix.browser}}

  unit-test-edge:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
      - run: sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
      - run: sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
      - run: sudo rm microsoft.gpg
      - run: sudo apt update
      - run: sudo apt install microsoft-edge-dev
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run test:edge


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run lint
