# Adapted from https://blog.testproject.io/2021/02/01/using-github-actions-to-run-automated-tests/
name: pull-request
on:
  pull_request:
    # branches: [ main ]

jobs:
  unit-test:
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    runs-on: ubuntu-latest
    name: unit-test-${{ matrix.browser }}
    steps:
      - uses: actions/checkout@v2
      # `cache` option uses https://github.com/actions/cache under the hood with less config.
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run test:${{matrix.browser}}

  unit-test-edge:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run test:edge

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run lint
